//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.225
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Rider.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Rider.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A propos.
        /// </summary>
        public static string AboutAppBarTitle {
            get {
                return ResourceManager.GetString("AboutAppBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Developpeur web - Bordeaux (France)
        ///Ruby on Rails.
        /// </summary>
        public static string AboutCollaboratorContent {
            get {
                return ResourceManager.GetString("AboutCollaboratorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci a Pierre Jambet.
        /// </summary>
        public static string AboutCollaboratorTitle {
            get {
                return ResourceManager.GetString("AboutCollaboratorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BeRider utilise les donnees gps de votre telephone afin de determiner les centres d&apos;equipements les plus proches de votre position. Ces informations sont enregistrees uniquement si vous souhaitez sauvegarder votre parcours. Aucune diffusion n&apos;est faites de notre part. Activer ou desactiver cette fonctionnalite a tout moment..
        /// </summary>
        public static string AboutLocationServicePolicy {
            get {
                return ResourceManager.GetString("AboutLocationServicePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service de Geolocalisation.
        /// </summary>
        public static string AboutLocationServicePolicyTitle {
            get {
                return ResourceManager.GetString("AboutLocationServicePolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Developpeur mobile - Bordeaux (France)
        ///IOS - Android - Windows Phone 7.
        /// </summary>
        public static string AboutPersonalContent {
            get {
                return ResourceManager.GetString("AboutPersonalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Par Loic Duparc.
        /// </summary>
        public static string AboutPersonalTitle {
            get {
                return ResourceManager.GetString("AboutPersonalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à donner votre avis.
        /// </summary>
        public static string AboutRateAppContent {
            get {
                return ResourceManager.GetString("AboutRateAppContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre evaluation ?.
        /// </summary>
        public static string AboutRateAppTitle {
            get {
                return ResourceManager.GetString("AboutRateAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mentions legales.
        /// </summary>
        public static string AboutSubTitle {
            get {
                return ResourceManager.GetString("AboutSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à contacter l&apos;equipe.
        /// </summary>
        public static string AboutSupportContent {
            get {
                return ResourceManager.GetString("AboutSupportContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suggestions, commentaires, support ?.
        /// </summary>
        public static string AboutSupportTitle {
            get {
                return ResourceManager.GetString("AboutSupportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à BeRider.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à be.
        /// </summary>
        public static string ApplicationTitleFirst {
            get {
                return ResourceManager.GetString("ApplicationTitleFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rider.
        /// </summary>
        public static string ApplicationTitleSecond {
            get {
                return ResourceManager.GetString("ApplicationTitleSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à support.
        /// </summary>
        public static string FeedBack {
            get {
                return ResourceManager.GetString("FeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Centrer.
        /// </summary>
        public static string LockerAppBarTitle {
            get {
                return ResourceManager.GetString("LockerAppBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode Carte.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Carte.
        /// </summary>
        public static string MapAppBarTitle {
            get {
                return ResourceManager.GetString("MapAppBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Navigation en temps reel.
        /// </summary>
        public static string MapSubTitle {
            get {
                return ResourceManager.GetString("MapSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode suivant.
        /// </summary>
        public static string NextMapTileAppBarTitle {
            get {
                return ResourceManager.GetString("NextMapTileAppBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Capturer un photo.
        /// </summary>
        public static string PhotosAppBarTitle {
            get {
                return ResourceManager.GetString("PhotosAppBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mode precedent.
        /// </summary>
        public static string PreviousMapTileAppBarTitle {
            get {
                return ResourceManager.GetString("PreviousMapTileAppBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à demarrer la session.
        /// </summary>
        public static string sessionStartAppBarTitle {
            get {
                return ResourceManager.GetString("sessionStartAppBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à stopper la session.
        /// </summary>
        public static string sessionStopAppBarTitle {
            get {
                return ResourceManager.GetString("sessionStopAppBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parametres.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parametres.
        /// </summary>
        public static string SettingsAppBarTitle {
            get {
                return ResourceManager.GetString("SettingsAppBarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langage.
        /// </summary>
        public static string SettingsLanguage {
            get {
                return ResourceManager.GetString("SettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Desactive.
        /// </summary>
        public static string SettingsLocationServiceModeDisabled {
            get {
                return ResourceManager.GetString("SettingsLocationServiceModeDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Active.
        /// </summary>
        public static string SettingsLocationServiceModeEnabled {
            get {
                return ResourceManager.GetString("SettingsLocationServiceModeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Service de localisation.
        /// </summary>
        public static string SettingsLocationServiceTitle {
            get {
                return ResourceManager.GetString("SettingsLocationServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configuration de l&apos;application.
        /// </summary>
        public static string SettingsSubTitle {
            get {
                return ResourceManager.GetString("SettingsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unites.
        /// </summary>
        public static string SettingsUnit {
            get {
                return ResourceManager.GetString("SettingsUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poids (kg).
        /// </summary>
        public static string SettingsWeight {
            get {
                return ResourceManager.GetString("SettingsWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1.0.0.0.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
